name: RPM Build (Fedora 40 - x86-64)
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:40
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:
    - uses: actions/checkout@v2

    - name: Setup RPM Source
      run: mkdir -p ./SOURCES && tar -pczf ./SOURCES/fedora-kernel-manager.tar.gz  --exclude="../$(basename "$PWD")/SOURCES/fedora-kernel-manager.tar.gz" ../$(basename "$PWD")

    - name: Get RPM Spec BuildRequires
      run: dnf install wget cpio mock tar pykickstart fedpkg libvirt fedora-packager rpmdevtools 'dnf-command(builddep)' -y && dnf builddep fedora-kernel-manager.spec -y

    - name: Build RPM package
      run: rpmbuild -bb fedora-kernel-manager.spec --define "_rpmdir $(pwd)/packages" --define "_topdir $(pwd)/"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Binary RPM
        path: packages/x86_64/
